package com.aymanelbanhawy.enterprisepdf.app.editor

import com.aymanelbanhawy.aiassistant.core.AiProviderDraft
import com.aymanelbanhawy.aiassistant.core.AssistantPrivacyMode
import com.aymanelbanhawy.editor.core.collaboration.ReviewFilterModel
import com.aymanelbanhawy.editor.core.connectors.ConnectorAccountDraft
import com.aymanelbanhawy.editor.core.enterprise.AdminPolicyModel
import com.aymanelbanhawy.editor.core.enterprise.LicensePlan
import com.aymanelbanhawy.editor.core.enterprise.PrivacySettingsModel
import com.aymanelbanhawy.editor.core.enterprise.TenantConfigurationModel
import com.aymanelbanhawy.editor.core.forms.SignatureCapture
import com.aymanelbanhawy.editor.core.forms.SignatureKind
import com.aymanelbanhawy.editor.core.model.AnnotationModel
import com.aymanelbanhawy.editor.core.model.AnnotationTool
import com.aymanelbanhawy.editor.core.model.EditorAction
import com.aymanelbanhawy.editor.core.model.FontFamilyToken
import com.aymanelbanhawy.editor.core.model.PageEditModel
import com.aymanelbanhawy.editor.core.model.TextAlignment
import com.aymanelbanhawy.editor.core.ocr.OcrSettingsModel
import com.aymanelbanhawy.editor.core.scan.ScanImportOptions
import com.aymanelbanhawy.editor.core.security.DocumentPermissionModel
import com.aymanelbanhawy.editor.core.security.MetadataScrubOptionsModel
import com.aymanelbanhawy.editor.core.security.TenantPolicyHooksModel
import com.aymanelbanhawy.editor.core.session.EditorSessionEvent


data class EditorScreenCallbacks(
    val onActionSelected: (EditorAction) -> Unit,
    val onDocumentLoaded: (Int) -> Unit,
    val onPageChanged: (Int, Int) -> Unit,
    val onToolSelected: (AnnotationTool) -> Unit,
    val onAnnotationCreated: (AnnotationModel) -> Unit,
    val onAnnotationUpdated: (AnnotationModel, AnnotationModel) -> Unit,
    val onAnnotationSelectionChanged: (Int, Set<String>) -> Unit,
    val onFormFieldTapped: (String) -> Unit,
    val onPageEditSelectionChanged: (Int, String?) -> Unit,
    val onPageEditUpdated: (PageEditModel, PageEditModel) -> Unit,
    val onSidebarToggle: () -> Unit,
    val onDeleteSelected: () -> Unit,
    val onDuplicateSelected: () -> Unit,
    val onRecolorSelected: (String) -> Unit,
    val onSelectAnnotation: (String) -> Unit,
    val onSelectFormField: (String) -> Unit,
    val onTextFieldChanged: (String, String) -> Unit,
    val onBooleanFieldChanged: (String, Boolean) -> Unit,
    val onChoiceFieldChanged: (String, String) -> Unit,
    val onSaveFormProfile: (String) -> Unit,
    val onApplyFormProfile: (String) -> Unit,
    val onExportFormData: () -> Unit,
    val onOpenPdf: () -> Unit,
    val onOpenFromFiles: () -> Unit,
    val onOpenRecentDocument: (RecentDocumentUiState) -> Unit,
    val onImportProfile: () -> Unit,
    val onOpenSignatureCapture: (String) -> Unit,
    val onApplySavedSignature: (String, String) -> Unit,
    val onDismissSignatureCapture: () -> Unit,
    val onSaveSignatureCapture: (String, SignatureKind, SignatureCapture) -> Unit,
    val onAddTextBox: () -> Unit,
    val onAddImage: () -> Unit,
    val onSelectEditObject: (String) -> Unit,
    val onDeleteSelectedEdit: () -> Unit,
    val onDuplicateSelectedEdit: () -> Unit,
    val onReplaceSelectedImage: () -> Unit,
    val onSelectedEditTextChanged: (String) -> Unit,
    val onSelectedEditFontFamilyChanged: (FontFamilyToken) -> Unit,
    val onSelectedEditFontSizeChanged: (Float) -> Unit,
    val onSelectedEditColorChanged: (String) -> Unit,
    val onSelectedEditAlignmentChanged: (TextAlignment) -> Unit,
    val onSelectedEditLineSpacingChanged: (Float) -> Unit,
    val onSelectedEditOpacityChanged: (Float) -> Unit,
    val onSelectedEditRotationChanged: (Float) -> Unit,
    val onSearchQueryChanged: (String) -> Unit,
    val onSearch: () -> Unit,
    val onAssistantPromptChanged: (String) -> Unit,
    val onAskPdf: () -> Unit,
    val onSummarizeDocumentWithAi: () -> Unit,
    val onSummarizePageWithAi: () -> Unit,
    val onExtractActionItemsWithAi: () -> Unit,
    val onExplainSelectionWithAi: () -> Unit,
    val onSemanticSearchWithAi: () -> Unit,
    val onAskWorkspaceWithAi: () -> Unit,
    val onSummarizeWorkspaceWithAi: () -> Unit,
    val onCompareWorkspaceWithAi: () -> Unit,
    val onPinCurrentDocumentToAiWorkspace: () -> Unit,
    val onToggleAiWorkspaceDocument: (String, Boolean) -> Unit,
    val onUnpinAiWorkspaceDocument: (String) -> Unit,
    val onSaveAiWorkspaceSet: (String) -> Unit,
    val onAssistantPrivacyModeChanged: (AssistantPrivacyMode) -> Unit,
    val onAssistantProviderDraftChanged: (AiProviderDraft) -> Unit,
    val onSaveAssistantProvider: () -> Unit,
    val onRefreshAssistantProviders: () -> Unit,
    val onTestAssistantConnection: () -> Unit,
    val onCancelAssistantRequest: () -> Unit,
    val onOpenAssistantCitation: (Int) -> Unit,
    val onStartVoicePromptCapture: () -> Unit,
    val onStopVoicePromptCapture: () -> Unit,
    val onCancelVoicePromptCapture: () -> Unit,
    val onReadCurrentPageAloud: () -> Unit,
    val onReadSelectionAloud: () -> Unit,
    val onPauseReadAloud: () -> Unit,
    val onResumeReadAloud: () -> Unit,
    val onStopReadAloud: () -> Unit,
    val onAssistantAudioEnabledChanged: (Boolean) -> Unit,
    val onNextSearchHit: () -> Unit,
    val onPreviousSearchHit: () -> Unit,
    val onSelectSearchHit: (Int) -> Unit,
    val onUseRecentSearch: (String) -> Unit,
    val onOpenOutlineItem: (Int) -> Unit,
    val onCopySelectedText: () -> Unit,
    val onShareSelectedText: () -> Unit,
    val onOcrSettingsChanged: (OcrSettingsModel) -> Unit,
    val onSaveOcrSettings: () -> Unit,
    val onPauseOcr: (Int?) -> Unit,
    val onResumeOcr: (Int?) -> Unit,
    val onRerunOcr: (Int?) -> Unit,
    val onOpenOcrPage: (Int) -> Unit,
    val onShowScanImport: () -> Unit,
    val onDismissScanImport: () -> Unit,
    val onScanImportOptionsChanged: (ScanImportOptions) -> Unit,
    val onPickScanImages: () -> Unit,
    val onCreateShareLink: () -> Unit,
    val onCreateSnapshot: () -> Unit,
    val onSyncNow: () -> Unit,
    val workflowExportActions: EditorWorkflowExportActions,
    val onCreateFormTemplate: (String) -> Unit,
    val onCreateSignatureRequest: (String) -> Unit,
    val onCreateFormRequest: (String, String) -> Unit,
    val onSendWorkflowReminder: (String) -> Unit,
    val onMarkWorkflowRequestCompleted: (String) -> Unit,
    val onReviewFilterChanged: (ReviewFilterModel) -> Unit,
    val onAddReviewThread: (String, String) -> Unit,
    val onAddReviewReply: (String, String) -> Unit,
    val onToggleThreadResolved: (String, Boolean) -> Unit,
    val onStartThreadVoiceComment: () -> Unit,
    val onStopThreadVoiceComment: () -> Unit,
    val onCancelThreadVoiceComment: () -> Unit,
    val onStartReplyVoiceComment: (String) -> Unit,
    val onStopReplyVoiceComment: (String) -> Unit,
    val onCancelReplyVoiceComment: (String) -> Unit,
    val onPlayVoiceComment: (String) -> Unit,
    val onStopVoiceCommentPlayback: () -> Unit,
    val onConfigureAppLock: (Boolean, String, Boolean, Int) -> Unit,
    val onUnlockWithPin: (String) -> Unit,
    val onUnlockWithBiometric: () -> Unit,
    val onLockNow: () -> Unit,
    val onUpdatePermissions: (DocumentPermissionModel) -> Unit,
    val onUpdateTenantPolicy: (TenantPolicyHooksModel) -> Unit,
    val onUpdatePasswordProtection: (Boolean, String, String) -> Unit,
    val onUpdateWatermark: (Boolean, String) -> Unit,
    val onUpdateMetadataScrub: (MetadataScrubOptionsModel) -> Unit,
    val onInspectSecurity: () -> Unit,
    val onMarkRedaction: () -> Unit,
    val onPreviewRedactions: (Boolean) -> Unit,
    val onApplyRedactions: () -> Unit,
    val onRemoveRedaction: (String) -> Unit,
    val onExportAuditTrail: () -> Unit,
    val onSignInPersonal: (String) -> Unit,
    val onSignInEnterprise: (String, TenantConfigurationModel) -> Unit,
    val onSignOutEnterprise: () -> Unit,
    val onSetEnterprisePlan: (LicensePlan) -> Unit,
    val onUpdateEnterprisePrivacy: (PrivacySettingsModel) -> Unit,
    val onUpdateEnterprisePolicy: (AdminPolicyModel) -> Unit,
    val onGenerateDiagnosticsBundle: () -> Unit,
    val onRefreshEnterpriseRemote: () -> Unit,
    val onFlushEnterpriseTelemetry: () -> Unit,
    val onSaveConnectorAccount: (ConnectorAccountDraft) -> Unit,
    val onTestConnectorConnection: (String) -> Unit,
    val onOpenConnectorDocument: (String, String, String) -> Unit,
    val onSyncConnectorTransfers: () -> Unit,
    val onCleanupConnectorCache: () -> Unit,
    val onRefreshDiagnostics: () -> Unit,
    val onRepairRuntimeState: () -> Unit,
    val onCleanupRuntimeCaches: () -> Unit,
    val onSaveToConnectorEditable: () -> Unit,
    val onSaveToConnectorFlattened: () -> Unit,
    val onShareToConnectorEditable: () -> Unit,
    val onDismissConnectorExportDialog: () -> Unit,
    val onConnectorExportAccountChanged: (String) -> Unit,
    val onConnectorExportRemotePathChanged: (String) -> Unit,
    val onConnectorExportDisplayNameChanged: (String) -> Unit,
    val onSubmitConnectorExport: () -> Unit,
    val onRotatePage: () -> Unit,
    val onReorderPages: () -> Unit,
    val onUndo: () -> Unit,
    val onRedo: () -> Unit,
    val onSaveEditable: () -> Unit,
    val onSaveFlattened: () -> Unit,
    val onSaveAsEditable: () -> Unit,
    val onSaveAsFlattened: () -> Unit,
    val onShareRequested: (EditorSessionEvent.ShareDocument) -> Unit,
    val onShareTextRequested: (EditorSessionEvent.ShareText) -> Unit,
)
